--- # Playbook for testing waitFor
- hosts: apacheweb
  user: cloud_user
  gather_facts: no
  tasks:
    - name: Install Apache
      action: apt name=apache2 state=installed
    - name: Port 80 polling
      wait_for:
        port: 80
        state: started
    - name: lynx
      action: apt name=lynx state=present

      
